import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import QueryProvider from "@/components/query-provider";
import NavBar from "@/components/shared/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <QueryProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <main className="max-w-6xl min-h-screen mx-auto py-10 spasce-y-10 p-5">

                  <NavBar />
                  {children}

                </main>
            </ThemeProvider>

        </QueryProvider>
      </body>
    </html>
  );
}
